# action.yml
name: 'Run KOS Container'
description: 'Run a command in a new container'
inputs:
  run:
    description: 'Commands to run in container'
    required: true

runs:
  uses: addnab/docker-run-action@v3
  with:
    image: ghcr.io/cepawiel/dc-kos-base:gcc9-latest
    options: -v ${{ github.workspace }}:/src
    run: ${{ inputs.run }}

